import LITranslation from "./LITranslation";

const EnglishLocalization: LITranslation = {
    LanguageName: "English",
    OpenFile: "Open File",
    SaveFile: "Save File",
    NewFile: "New File",
    ImportLegacy: "Import Legacy",
    AddObject: "Add Object",
    AddLayer: "Add Layer",
    DeleteObject: "Delete Object",
    OpenInEditor: "Open in Editor",
    Undo: "Undo",
    Redo: "Redo",
    Publish: "Publish",
    Settings: "Settings",
    Name: "Name",
    Type: "Type",
    X: "X",
    Y: "Y",
    Z: "Z",
    XScale: "X Scale",
    YScale: "Y Scale",
    Rotation: "Rotation",
    Delete: "Delete",
    Reset: "Reset",
    Upload: "Upload",
    NothingUploaded: "Nothing Uploaded",
    Offset: "Offset",
    Zoom: "Zoom",
    Solid: "Is Solid",
    Visible: "Is Visible",
    BlocksLight: "Blocks Light",
    Points: "Points",
    Add: "Add",
    Remove: "Remove",
    AddCollider: "Add Collider",
    Range: "Range",
    OnlyFromBelow: "Only From Below",
    PrintToConsole: "Print to Console",
    Height: "Height",
    Length: "Length",
    Size: "Size",
    Download: "Download",
    Movement: "Movement",
    EntranceOffset: "Entrance Offset",
    ExitOffset: "Exit Offset",
    ShowName: "Show Name",
    ShowAdminTable: "Show on Admin Table",
    Default: "Default",
    DefaultDescription: "Default Description",
    DefaultLength: "Default Length",
    DefaultRoom: "Default Room",
    NoRoom: "No Room",
    NoShadows: "No Shadows",
    NoShadowBehavior: "Shadow Behavior",
    Count: "Count",
    MaxSpeed: "Max Speed",
    MinSpeed: "Min Speed",
    StepPresets: "Step Presets",
    StepVariants: "Step Variants",
    Priority: "Priority",
    Create: "Create %name%",
    AmbientSound: "Ambient Sound",
    Camera: "Camera",
    Collider: "Collider",
    Colliders: "Colliders",
    Console: "Console",
    Debug: "Debug",
    Ladder: "Ladder",
    Minimap: "Minimap",
    Platform: "Moving Platform",
    Room: "Room",
    Sabotage: "Sabotage",
    Sprite: "Sprite",
    Starfield: "Starfield",
    StepSound: "Step Sound",
    StepSounds: "Step Sounds",
    Task: "Task",
    Transform: "Transform",
    Vent: "Vent",
    Speed: "Speed",
    FloatingSprite: "Floating Sprite",
    DeleteLayerDialogTitle: "Delete Layer",
    DeleteLayerDialogText: "Would you like the objects in this layer to be deleted or demoted to the default layer?",
    DeleteLayerDeleteObjects: "Delete Objects",
    DeleteLayerDemoteObjects: "Demote Objects",
    Cancel: "Cancel",
    Elements: "Elements",
    Layers: "Layers",
    Teleporter: "Teleporter",
};

export default EnglishLocalization;