import LITranslation from "./LITranslation";

const PirateLocalization: LITranslation = {
    LanguageName: "Pirate",
    OpenFile: "Open yer file",
    SaveFile: "Save yer file",
    NewFile: "New file",
    ImportLegacy: "Import yer legacy",
    AddObject: "Add yer object",
    AddLayer: "Add yer layer",
    DeleteObject: "Walk the plank",
    OpenInEditor: "Sail to the Editor",
    Undo: "Undo",
    Redo: "Redo",
    Publish: "Publish",
    Settings: "Settings",
    Name: "Title",
    Type: "Quarters",
    X: "X",
    Y: "Y",
    Z: "Z",
    XScale: "X Scale",
    YScale: "Y Scale",
    Rotation: "Rotation",
    Delete: "Delete",
    Reset: "Walk the plank",
    Upload: "Show a leg",
    NothingUploaded: "No Chests",
    Offset: "Offset",
    Zoom: "Zoom",
    Solid: "Is Solid",
    Visible: "Is Visible",
    BlocksLight: "Blocks Light",
    Points: "X Marks the Spot",
    Add: "Add",
    Remove: "Remove",
    AddCollider: "Add yer Collider",
    Range: "Range",
    OnlyFromBelow: "Only Below Deck",
    PrintToConsole: "Land Ho",
    Height: "Height",
    Length: "Length",
    Size: "Size",
    Download: "Download",
    Movement: "Movement",
    EntranceOffset: "Entrance Offset",
    ExitOffset: "Exit Offset",
    ShowName: "Show yer Name",
    ShowAdminTable: "Show on yer Table",
    Default: "Default",
    DefaultDescription: "Default Description",
    DefaultLength: "Default Length",
    DefaultRoom: "Default Room",
    NoRoom: "No Room",
    NoShadows: "No Shadows",
    NoShadowBehavior: "Shadow Behavior",
    Count: "Count",
    MaxSpeed: "Max Speed",
    MinSpeed: "Min Speed",
    StepPresets: "Peg Presets",
    StepVariants: "Peg Variants",
    Priority: "Priority",
    Create: "Create %name%",
    AmbientSound: "Ambient Creaking",
    Camera: "Crows Nest",
    Collider: "Wall",
    Colliders: "Walls",
    Console: "Helm",
    Debug: "Debug",
    Ladder: "Jacob's Ladder",
    Minimap: "Map",
    Platform: "The Plank",
    Room: "Deck",
    Sabotage: "Blunder",
    Sprite: "Jolly Roger",
    Starfield: "Stars",
    StepSound: "Peg Sound",
    StepSounds: "Peg Sounds",
    Task: "Task",
    Transform: "Transform",
    Vent: "Bilge",
    DeleteLayerDialogTitle: "Delete Layer",
    DeleteLayerDialogText: "Would you like the objects in this layer to be deleted or demoted to the default layer?",
    DeleteLayerDeleteObjects: "Delete Objects",
    DeleteLayerDemoteObjects: "Demote Objects",
    Cancel: "Cancel",
    Elements: "Sea Creatures",
    Layers: "Leagues Under the Sea",
    Teleporter: "Teleporter",
    AllElements: "All Sea Creatures",
    SignIn: "Climb Abord",

};

export default PirateLocalization;