import LITranslation from "./LITranslation";

/**
 * Simplified Chinese Localization
 * Translated by @PAF_huier_cn#8777
 */
const SimplifiedChineseLocalization: LITranslation = {
    LanguageName: "简体中文",
    OpenFile: "打开文件",
    SaveFile: "保存文件",
    NewFile: "新建文件",
    ImportLegacy: "导入文件",
    AddObject: "新建物体",
    AddLayer: "新建图层",
    DeleteObject: "删除物体",
    OpenInEditor: "在编辑器中打开",
    Undo: "撤销",
    Redo: "重做",
    Publish: "发布地图",
    Settings: "设置",
    Name: "名称",
    Type: "类型",
    X: "X",
    Y: "Y",
    Z: "Z",
    XScale: "X轴长度",
    YScale: "Y轴长度",
    Rotation: "旋转",
    Delete: "删除",
    Reset: "重置",
    Upload: "上传",
    NothingUploaded: "没有上传任何东西",
    Offset: "移动",
    Zoom: "缩放",
    Solid: "坚固",
    Visible: "可视",
    BlocksLight: "挡光",
    Points: "积分",
    Add: "添加",
    Remove: "删除",
    AddCollider: "添加碰撞体",
    Range: "范围",
    OnlyFromBelow: "从下面看",
    PrintToConsole: "输出到控制台",
    Height: "高度",
    Length: "长度",
    Size: "尺寸",
    Download: "下载",
    Movement: "移动",
    EntranceOffset: "移动入口",
    ExitOffset: "移动出口",
    ShowName: "显示名称",
    ShowAdminTable: "显示在控制台上",
    Default: "默认",
    DefaultDescription: "默认描述",
    DefaultLength: "默认长度",
    DefaultRoom: "默认房间",
    NoRoom: "没有房间",
    NoShadows: "没有阴影",
    NoShadowBehavior: "阴影行为",
    Count: "计数",
    MaxSpeed: "最大速度",
    MinSpeed: "最小速度",
    StepPresets: "预设步骤",
    StepVariants: "变更步骤",
    Priority: "优先级",
    Create: "创建%name%",
    //AmbientSound: "环境音效",
    Camera: "摄像机",
    Collider: "碰撞",
    Colliders: "碰撞体",
    Console: "控制台",
    Debug: "调试",
    Ladder: "梯子",
    Minimap: "迷你地图",
    Platform: "移动平台",
    Room: "房间",
    Sabotage: "破坏",
    Sprite: "雪碧",
    Starfield: "星空",
    StepSound: "脚步声",
    StepSounds: "脚步声",
    Task: "任务",
    Transform: "转换",
    Vent: "发泄",
    Speed: "速度",
    FloatingSprite: "浮动精灵",
    DeleteLayerDialogTitle: "删除图层",
    DeleteLayerDialogText: "您希望删除此图层中的对象还是将其降级为默认图层？",
    DeleteLayerDeleteObjects: "删除物体",
    DeleteLayerDemoteObjects: "降级物体",
    Cancel: "取消",
    Elements: "元素",
    Layers: "图层",
    Teleporter: "传送器",
    AllElements: "所有元素",
    SignIn: "登入",
    SignOut: "登出",
    LIAPIPolicy: "LevelImposter API 政策",
    Warning: "警告",
    MobileWarning: "LevelImposter 编辑器不是为在移动设备上运行而设计的。 但是，您的里程可能会有所不同。",
    ChromeWarning: "虽然 LevelImposter Editor 可以与任何现代浏览器一起使用，但基于 Chromium 的浏览器（Google Chrome、Microsoft Edge、Brave）在处理更大的地图时渲染速度会更快。",
    OK: "确定",
    OpenDocs: "打开文档",
    DownloadMapImage: "下载地图图像",
    Yes: "确定",
    VerifyEmailError: "您的电子邮件地址尚未经过验证。 请检查您的电子邮件以获取验证链接。",
    PublishSuccess: "您的地图发布成功！",
    SignedInAs: "以%name%身份登录",
    LaunchMap: "发射地图",
    PublishInfo: "发布信息",
};

export default SimplifiedChineseLocalization;