export enum TaskLength {
    Short = "Short",
    Long = "Long",
    Common = "Common"
}

export const AUTaskLengthDB = {
    "task-id": TaskLength.Common,
    "task-keys": TaskLength.Common,
    "task-pass": TaskLength.Common,
    "task-wires": TaskLength.Common,
    "task-code": TaskLength.Common,
    "task-tree": TaskLength.Short,
    "task-counting": TaskLength.Short,
    "task-artifacts": TaskLength.Short,
    "task-oxygen": TaskLength.Short,
    "task-garbage": TaskLength.Short,
    "task-chart": TaskLength.Short,
    "task-medscan": TaskLength.Short,
    "task-weapons": TaskLength.Short,
    "task-telescope": TaskLength.Short,
    "task-drill": TaskLength.Short,
    "task-temp1": TaskLength.Short,
    "task-temp2": TaskLength.Short,
    "task-divert1": TaskLength.Short,
    "task-crystal": TaskLength.Short,
    "task-sort": TaskLength.Short,
    "task-shields": TaskLength.Short,
    "task-weather": TaskLength.Short,
    "task-vending": TaskLength.Short,
    "task-process": TaskLength.Short,
    "task-diagnostics": TaskLength.Short,
    "task-stabilize": TaskLength.Short,
    "task-showers": TaskLength.Short,
    "task-burger": TaskLength.Short,
    "task-decontaminate": TaskLength.Short,
    "task-rifles1": TaskLength.Short,
    "task-pistols1": TaskLength.Short,
    "task-records1": TaskLength.Short,
    "task-mannequin": TaskLength.Short,
    "task-toilet": TaskLength.Short,
    "task-towels1": TaskLength.Short,
    "task-stabilize2": TaskLength.Short,
    "task-ruby": TaskLength.Short,
    "task-simonsays": TaskLength.Long,
    "task-fuel1": TaskLength.Long,
    "task-waterwheel1": TaskLength.Long,
    "task-samples": TaskLength.Long,
    "task-waterjug1": TaskLength.Long,
    "task-router": TaskLength.Long,
    "task-node": TaskLength.Long,
    "task-plants1": TaskLength.Long,
    "task-align1": TaskLength.Long,
    "task-tapes": TaskLength.Long,
    "task-photos": TaskLength.Long,
    "task-garbage2": TaskLength.Long,
    "task-garbage3": TaskLength.Long,
    "task-garbage4": TaskLength.Long,
    "task-safe": TaskLength.Long,
    "task-breakers": TaskLength.Long,
    "task-fans1": TaskLength.Long,
    "task-distributor": TaskLength.Long,
    "task-download": TaskLength.Short,
    "task-upload": TaskLength.Short,
    "task-leaves": TaskLength.Short,
    "task-hoist": TaskLength.Long,
    "task-replaceparts1": TaskLength.Common,
    "task-replaceparts2": TaskLength.Common,
    "task-mineores": TaskLength.Long,
    "task-radio": TaskLength.Short,
    "task-vegetables1": TaskLength.Long,
    "task-vegetables2": TaskLength.Long,
    "task-samples1": TaskLength.Common,
    "task-samples2": TaskLength.Common,
    "task-egg1": TaskLength.Long,
    "task-egg2": TaskLength.Long,
    "task-seashells": TaskLength.Short,
    "task-fish1": TaskLength.Long,
    "task-fish2": TaskLength.Long,
    "task-generator": TaskLength.Short,
    "task-frisbee": TaskLength.Short,
    "task-weights": TaskLength.Short,
    "task-sandcastle": TaskLength.Short,
    "task-marshmallow1": TaskLength.Common,
    "task-marshmallow2": TaskLength.Common,
};